services:
  material-management-fe:
    image: material-management-fe:latest
    container_name: material-management-fe
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://192.168.1.16:8088/api/v1}
